### ISSUE TITLE
is it even safe to talk to hackerbot?

### ISSUE THREAD

**Issue by ntdkhiem** [omergunal/hackerbot#5]
Are you aware that the Nameless chat robot logs and records all converstaions?

Then that mean every things I did like mimipenguin still being recorded too?

**Comment by omergunal** [comment]
I don't think anyone logging and recording your data, i used aiml for chatbot. you can check this url : https://pypi.python.org/pypi/aiml 
and this is mimipenguin's page,you can look source code : https://github.com/huntergregal/mimipenguin

**Comment by ntdkhiem** [comment]
Thanks

**Comment by omergunal** [comment]
my pleasure
