### ISSUE TITLE
Friendly Reminder to Never Upload Your Samples to VirusTotal 

### ISSUE THREAD

**Issue by Armanmd** [omergunal/hackerbot#6]
_**hello plz check this**_ link [link](https://null-byte.wonderhowto.com/news/antivirus-bypass-friendly-reminder-never-upload-your-samples-virustotal-0163390/)

if you can change your virus scanner to http://nodistribute.com/ (The results of the scans are never distributed.)

**Comment by omergunal** [comment]
i understand you but its limited for 5 times scanning. user should buy premium account

**Comment by Armanmd** [comment]
@omergunal i khow , but more than five are not bad for a normal person

**Comment by Armanmd** [comment]
Or you can use both of them

**Comment by Armanmd** [comment]
[check this link](https://www.rekings.com/no-distribute-scanners/)

**Comment by omergunal** [comment]
ok. i will check it, thanks
